/*   */ package com.sun.tools.jdi.resources;
/*   */ 
/*   */ import java.util.ListResourceBundle;
/*   */ 
/*   */ public final class jdi_ja extends ListResourceBundle {
/*   */   protected final Object[][] getContents() {
/* 7 */     return new Object[][] { { "false", "false" }, { "generic_attaching.address", "VMに接続するアドレス" }, { "generic_attaching.address.label", "アドレス" }, { "generic_attaching.timeout", "接続を待つ間のタイムアウト " }, { "generic_attaching.timeout.label", "タイムアウト" }, { "generic_listening.address", "VMへの接続をリスニングするアドレス" }, { "generic_listening.address.label", "アドレス" }, { "generic_listening.timeout", "接続を待つ間のタイムアウト" }, { "generic_listening.timeout.label", "タイムアウト" }, { "memory_attaching.description", "共有メモリーでその他のVMに接続します" }, { "memory_attaching.name", "VMへの接続に使用される共有メモリー領域名" }, { "memory_attaching.name.label", "名前" }, { "memory_listening.description", "その他のVMにより開始される共有メモリー接続を受け入れます" }, { "memory_listening.name", "VMへの接続をリスニングするための共有メモリー領域名" }, { "memory_listening.name.label", "名前" }, { "memory_transportservice.description", "共有メモリー接続でデバッガとターゲットを接続します" }, { "process_attaching.description", "デバッグするプロセスにプロセスID (pid)を使用して接続します" }, { "process_attaching.pid", "pid" }, { "process_attaching.pid.label", "デバッグするプロセスID (pid)" }, { "raw.address", "rawコマンド実行後に接続をリスニングするアドレス" }, { "raw.address.label", "アドレス" }, { "raw.command", "デバッグするアプリケーションVMを起動させるrawコマンド" }, { "raw.command.label", "コマンド" }, { "raw.description", "ユーザーが指定したコマンド行を使用してターゲットを起動し、接続します" }, { "raw.quote", "単一のコマンド行引数内にスペースで区切られたテキストを結び付けるために使用される文字" }, { "raw.quote.label", "引用符" }, { "socket_attaching.description", "ソケットでその他のVMに接続します" }, { "socket_attaching.host", "VMに接続するマシン名" }, { "socket_attaching.host.label", "ホスト" }, { "socket_attaching.port", "VMに接続するポート番号" }, { "socket_attaching.port.label", "ポート" }, { "socket_listening.description", "その他のVMにより開始されるソケット接続を受入れます" }, { "socket_listening.localaddr", "リスナーのバインド先ローカル・アドレス" }, { "socket_listening.localaddr.label", "ローカル・アドレス" }, { "socket_listening.port", "VMへの接続をリスニングするポート番号" }, { "socket_listening.port.label", "ポート" }, { "socket_transportservice.description", "TCP接続でデバッガとターゲットを接続します" }, { "sun.description", "SunのJava VMコマンド行を使用してターゲットを起動し、接続します" }, { "sun.home", "SDKのホーム・ディレクトリまたは、アプリケーションの起動に使用される実行環境" }, { "sun.home.label", "ホーム " }, { "sun.init_suspend", "メインの実行前にすべてのスレッドが中断されます。" }, { "sun.init_suspend.label", "中断" }, { "sun.main", "メイン・クラスと引数、または-jarがオプションの場合にはメインjarファイルと引数" }, { "sun.main.label", "メイン" }, { "sun.options", "起動するVMのオプション" }, { "sun.options.label", "オプション" }, { "sun.quote", "単一のコマンド行引数内にスペースで区切られたテキストを結び付けるために使用される文字" }, { "sun.quote.label", "引用符" }, { "sun.vm_exec", "Java VM起動ツール名" }, { "sun.vm_exec.label", "起動ツール" }, { "true", "true" }, { "version_format", "Java Debug Interface(リファレンス実装)バージョン{0}.{1}\n{2}" } };
/*   */   }
/*   */ }


/* Location:              C:\Program Files\Java\jdk1.8.0_211\lib\tools.jar!\com\sun\tools\jdi\resources\jdi_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */