/*     */ package sun.security.tools.jarsigner;
/*     */ 
/*     */ import java.util.ListResourceBundle;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class Resources_ja
/*     */   extends ListResourceBundle
/*     */ {
/*  35 */   private static final Object[][] contents = new Object[][] { { "SPACE", " " }, { "2SPACE", "  " }, { "6SPACE", "      " }, { "COMMA", ", " }, { "provName.not.a.provider", "{0}はプロバイダではありません" }, { "signerClass.is.not.a.signing.mechanism", "{0}は署名メカニズムではありません" }, { "jarsigner.error.", "jarsignerエラー: " }, { "Illegal.option.", "不正なオプション: " }, { ".keystore.must.be.NONE.if.storetype.is.{0}", "-storetypeが{0}の場合、-keystoreはNONEである必要があります" }, { ".keypass.can.not.be.specified.if.storetype.is.{0}", "-storetypeが{0}の場合、-keypassは指定できません" }, { "If.protected.is.specified.then.storepass.and.keypass.must.not.be.specified", "-protectedを指定する場合は、-storepassおよび-keypassを指定しないでください" }, { "If.keystore.is.not.password.protected.then.storepass.and.keypass.must.not.be.specified", "キーストアがパスワードで保護されていない場合、-storepassおよび-keypassを指定しないでください" }, { "Usage.jarsigner.options.jar.file.alias", "使用方法: jarsigner [options] jar-file alias" }, { ".jarsigner.verify.options.jar.file.alias.", "       jarsigner -verify [options] jar-file [alias...]" }, { ".keystore.url.keystore.location", "[-keystore <url>]           キーストアの位置" }, { ".storepass.password.password.for.keystore.integrity", "[-storepass <password>]     キーストア整合性のためのパスワード" }, { ".storetype.type.keystore.type", "[-storetype <type>]         キーストアの型" }, { ".keypass.password.password.for.private.key.if.different.", "[-keypass <password>]       秘密キーのパスワード(異なる場合)" }, { ".certchain.file.name.of.alternative.certchain.file", "[-certchain <file>]         代替証明書チェーン・ファイルの名前" }, { ".sigfile.file.name.of.SF.DSA.file", "[-sigfile <file>]           .SF/.DSAファイルの名前" }, { ".signedjar.file.name.of.signed.JAR.file", "[-signedjar <file>]         署名付きJARファイルの名前" }, { ".digestalg.algorithm.name.of.digest.algorithm", "[-digestalg <algorithm>]    ダイジェスト・アルゴリズムの名前" }, { ".sigalg.algorithm.name.of.signature.algorithm", "[-sigalg <algorithm>]       シグネチャ・アルゴリズムの名前" }, { ".verify.verify.a.signed.JAR.file", "[-verify]                   署名付きJARファイルの検証" }, { ".verbose.suboptions.verbose.output.when.signing.verifying.", "[-verbose[:suboptions]]     署名/検証時の詳細出力。" }, { ".suboptions.can.be.all.grouped.or.summary", "                            サブオプションとして、all、groupedまたはsummaryを使用できます" }, { ".certs.display.certificates.when.verbose.and.verifying", "[-certs]                    詳細出力および検証時に証明書を表示" }, { ".tsa.url.location.of.the.Timestamping.Authority", "[-tsa <url>]                タイムスタンプ局の場所" }, { ".tsacert.alias.public.key.certificate.for.Timestamping.Authority", "[-tsacert <alias>]          タイムスタンプ局の公開キー証明書" }, { ".tsapolicyid.tsapolicyid.for.Timestamping.Authority", "[-tsapolicyid <oid>]        タイムスタンプ局のTSAPolicyID" }, { ".tsadigestalg.algorithm.of.digest.data.in.timestamping.request", "[-tsadigestalg <algorithm>] タイムスタンプ・リクエストのダイジェスト・データのアルゴリズム" }, { ".altsigner.class.class.name.of.an.alternative.signing.mechanism", "[-altsigner <class>]        代替署名メカニズムのクラス名" }, { ".altsignerpath.pathlist.location.of.an.alternative.signing.mechanism", "[-altsignerpath <pathlist>] 代替署名メカニズムの場所" }, { ".internalsf.include.the.SF.file.inside.the.signature.block", "[-internalsf]               シグネチャ・ブロックに.SFファイルを含める" }, { ".sectionsonly.don.t.compute.hash.of.entire.manifest", "[-sectionsonly]             マニフェスト全体のハッシュは計算しない" }, { ".protected.keystore.has.protected.authentication.path", "[-protected]                キーストアには保護された認証パスがある" }, { ".providerName.name.provider.name", "[-providerName <name>]      プロバイダ名" }, { ".providerClass.class.name.of.cryptographic.service.provider.s", "[-providerClass <class>     暗号化サービス・プロバイダの名前" }, { ".providerArg.arg.master.class.file.and.constructor.argument", "  [-providerArg <arg>]] ... マスター・クラス・ファイルとコンストラクタの引数" }, { ".strict.treat.warnings.as.errors", "[-strict]                   警告をエラーとして処理" }, { "Option.lacks.argument", "オプションに引数がありません" }, { "Please.type.jarsigner.help.for.usage", "使用方法についてはjarsigner -helpと入力してください" }, { "Please.specify.jarfile.name", "jarfile名を指定してください" }, { "Please.specify.alias.name", "別名を指定してください" }, { "Only.one.alias.can.be.specified", "別名は1つのみ指定できます" }, { "This.jar.contains.signed.entries.which.is.not.signed.by.the.specified.alias.es.", "このjarに含まれる署名済エントリは、指定された別名によって署名されていません。" }, { "This.jar.contains.signed.entries.that.s.not.signed.by.alias.in.this.keystore.", "このjarに含まれる署名済エントリは、このキーストア内の別名によって署名されていません。" }, { "s", "s" }, { "m", "m" }, { "k", "k" }, { "i", "i" }, { ".and.d.more.", "(他にも%d個)" }, { ".s.signature.was.verified.", "  s=シグネチャが検証されました " }, { ".m.entry.is.listed.in.manifest", "  m=エントリがマニフェスト内にリストされます" }, { ".k.at.least.one.certificate.was.found.in.keystore", "  k=1つ以上の証明書がキーストアで検出されました" }, { ".i.at.least.one.certificate.was.found.in.identity.scope", "  i=1つ以上の証明書がアイデンティティ・スコープで検出されました" }, { ".X.not.signed.by.specified.alias.es.", "  X =指定した別名で署名されていません" }, { "no.manifest.", "マニフェストは存在しません。" }, { ".Signature.related.entries.", "(シグネチャ関連エントリ)" }, { ".Unsigned.entries.", "(署名なしのエントリ)" }, { "jar.is.unsigned", "jarは署名されていません。" }, { "jar.treated.unsigned", "警告: 署名が構文解析できないか検証できないため、このjarは署名なしとして扱われます。詳細は、デバッグを有効にして(-J-Djava.security.debug=jar) jarsignerを再実行してください。" }, { "jar.treated.unsigned.see.weak", "このjarは、現在無効になっている弱いアルゴリズムで署名されているため、署名なしとして扱われます。\n\n詳細は、-verboseオプションを使用してjarsignerを再実行してください。" }, { "jar.treated.unsigned.see.weak.verbose", "警告: このjarは、セキュリティ・プロパティによって現在無効になっている弱いアルゴリズムで署名されているため、署名なしとして扱われます:" }, { "jar.signed.", "jarは署名されました。" }, { "jar.signed.with.signer.errors.", "jarは署名されました - 署名者エラーがあります。" }, { "jar.verified.", "jarが検証されました。" }, { "jar.verified.with.signer.errors.", "jarは検証されました - 署名者エラーがあります。" }, { "history.with.ts", "- 署名者: \"%1$s\"\n    ダイジェスト・アルゴリズム: %2$s\n    署名アルゴリズム: %3$s、%4$s\n  タイムスタンプ付加者: \"%6$s\" 日時: %5$tc\n    タイムスタンプのダイジェスト・アルゴリズム: %7$s\n    タイムスタンプの署名アルゴリズム: %8$s、%9$s" }, { "history.without.ts", "- 署名者: \"%1$s\"\n    ダイジェスト・アルゴリズム: %2$s\n    署名アルゴリズム: %3$s、%4$s" }, { "history.unparsable", "- 署名関連ファイル%sを解析できません" }, { "history.nosf", "- 署名関連ファイルMETA-INF/%s.SFがありません" }, { "history.nobk", "- 署名関連ファイルMETA-INF/%s.SFのブロック・ファイルがありません" }, { "with.weak", "%s (弱)" }, { "key.bit", "%dビット・キー" }, { "key.bit.weak", "%dビット・キー(弱)" }, { "jarsigner.", "jarsigner: " }, { "signature.filename.must.consist.of.the.following.characters.A.Z.0.9.or.", "シグネチャのファイル名に使用できる文字は、A-Z、0-9、_、- のみです。" }, { "unable.to.open.jar.file.", "次のjarファイルを開くことができません: " }, { "unable.to.create.", "作成できません: " }, { ".adding.", "   追加中: " }, { ".updating.", " 更新中: " }, { ".signing.", "  署名中: " }, { "attempt.to.rename.signedJarFile.to.jarFile.failed", "{0}の名前を{1}に変更しようとしましたが失敗しました" }, { "attempt.to.rename.jarFile.to.origJar.failed", "{0}の名前を{1}に変更しようとしましたが失敗しました" }, { "unable.to.sign.jar.", "jarに署名できません: " }, { "Enter.Passphrase.for.keystore.", "キーストアのパスワードを入力してください: " }, { "keystore.load.", "キーストアのロード: " }, { "certificate.exception.", "証明書例外: " }, { "unable.to.instantiate.keystore.class.", "キーストア・クラスのインスタンスを生成できません: " }, { "Certificate.chain.not.found.for.alias.alias.must.reference.a.valid.KeyStore.key.entry.containing.a.private.key.and", "次の証明書チェーンが見つかりません: {0}。{1}は、秘密キーおよび対応する公開キー証明書チェーンを含む有効なKeyStoreキー・エントリを参照する必要があります。" }, { "File.specified.by.certchain.does.not.exist", "-certchainで指定されているファイルは存在しません" }, { "Cannot.restore.certchain.from.file.specified", "指定されたファイルから証明書チェーンを復元できません" }, { "Certificate.chain.not.found.in.the.file.specified.", "証明書チェーンは指定されたファイルに見つかりません。" }, { "found.non.X.509.certificate.in.signer.s.chain", "署名者の連鎖内で非X.509証明書が検出されました" }, { "incomplete.certificate.chain", "不完全な証明書チェーン" }, { "Enter.key.password.for.alias.", "{0}のキー・パスワードを入力してください: " }, { "unable.to.recover.key.from.keystore", "キーストアからキーを復元できません" }, { "key.associated.with.alias.not.a.private.key", "{0}と関連付けられたキーは、秘密キーではありません" }, { "you.must.enter.key.password", "キー・パスワードを入力する必要があります" }, { "unable.to.read.password.", "パスワードを読み込めません: " }, { "certificate.is.valid.from", "証明書は{0}から{1}まで有効です" }, { "certificate.expired.on", "証明書は{0}に失効しました" }, { "certificate.is.not.valid.until", "証明書は{0}まで有効ではありません" }, { "certificate.will.expire.on", "証明書は{0}に失効します" }, { ".Invalid.certificate.chain.", "[無効な証明書チェーン: " }, { ".Invalid.TSA.certificate.chain.", "[無効なTSA証明書チェーン: " }, { "requesting.a.signature.timestamp", "シグネチャ・タイムスタンプのリクエスト" }, { "TSA.location.", "TSAの場所: " }, { "TSA.certificate.", "TSA証明書: " }, { "no.response.from.the.Timestamping.Authority.", "タイムスタンプ局からのレスポンスがありません。ファイアウォールを介して接続するときは、必要に応じてHTTPまたはHTTPSプロキシを指定してください。jarsignerに次のオプションを指定してください:" }, { "or", "または" }, { "Certificate.not.found.for.alias.alias.must.reference.a.valid.KeyStore.entry.containing.an.X.509.public.key.certificate.for.the", "証明書が見つかりませんでした: {0}。{1}はタイムスタンプ局のX.509公開キー証明書が含まれている有効なKeyStoreエントリを参照する必要があります。" }, { "using.an.alternative.signing.mechanism", "代替署名メカニズムの使用" }, { "entry.was.signed.on", "エントリは{0}に署名されました" }, { "Warning.", "警告: " }, { "Error.", "エラー: " }, { "...Signer", ">>> 署名者" }, { "...TSA", ">>> TSA" }, { "trusted.certificate", "信頼できる証明書" }, { "This.jar.contains.unsigned.entries.which.have.not.been.integrity.checked.", "このjarには、整合性チェックをしていない署名なしのエントリが含まれています。 " }, { "This.jar.contains.entries.whose.signer.certificate.has.expired.", "このjarには、署名者の証明書が期限切れのエントリが含まれています。 " }, { "This.jar.contains.entries.whose.signer.certificate.will.expire.within.six.months.", "このjarには、署名者の証明書が6か月以内に期限切れとなるエントリが含まれています。 " }, { "This.jar.contains.entries.whose.signer.certificate.is.not.yet.valid.", "このjarには、署名者の証明書がまだ有効になっていないエントリが含まれています。 " }, { "This.jar.contains.entries.whose.signer.certificate.is.self.signed.", "このjarには、署名者の証明書が自己署名されているエントリが含まれています。 " }, { "Re.run.with.the.verbose.option.for.more.details.", "詳細は、-verboseオプションを使用して再実行してください。" }, { "Re.run.with.the.verbose.and.certs.options.for.more.details.", "詳細は、-verboseおよび-certsオプションを使用して再実行してください。" }, { "The.signer.certificate.has.expired.", "署名者の証明書は期限切れです。" }, { "The.timestamp.expired.1.but.usable.2", "タイムスタンプは%1$tY-%1$tm-%1$tdに期限切れになります。ただし、JARは署名者の証明書が%2$tY-%2$tm-%2$tdに期限切れになるまで有効です。" }, { "The.timestamp.has.expired.", "タイムスタンプは期限切れになりました。" }, { "The.signer.certificate.will.expire.within.six.months.", "署名者の証明書は6か月以内に期限切れになります。" }, { "The.timestamp.will.expire.within.one.year.on.1", "タイムスタンプは1年以内の%1$tY-%1$tm-%1$tdに期限切れになります。" }, { "The.timestamp.will.expire.within.one.year.on.1.but.2", "タイムスタンプは1年以内の%1$tY-%1$tm-%1$tdに期限切れになります。ただし、JARは署名者の証明書が%2$tY-%2$tm-%2$tdに期限切れになるまで有効です。" }, { "The.signer.certificate.is.not.yet.valid.", "署名者の証明書はまだ有効になっていません。" }, { "The.signer.certificate.s.KeyUsage.extension.doesn.t.allow.code.signing.", "署名者証明書のKeyUsage拡張機能では、コード署名は許可されません。" }, { "The.signer.certificate.s.ExtendedKeyUsage.extension.doesn.t.allow.code.signing.", "署名者証明書のExtendedKeyUsage拡張機能では、コード署名は許可されません。" }, { "The.signer.certificate.s.NetscapeCertType.extension.doesn.t.allow.code.signing.", "署名者証明書のNetscapeCertType拡張機能では、コード署名は許可されません。" }, { "This.jar.contains.entries.whose.signer.certificate.s.KeyUsage.extension.doesn.t.allow.code.signing.", "このjarには、署名者証明書のKeyUsage拡張機能がコード署名を許可しないエントリが含まれています。" }, { "This.jar.contains.entries.whose.signer.certificate.s.ExtendedKeyUsage.extension.doesn.t.allow.code.signing.", "このjarには、署名者証明書のExtendedKeyUsage拡張機能がコード署名を許可しないエントリが含まれています。" }, { "This.jar.contains.entries.whose.signer.certificate.s.NetscapeCertType.extension.doesn.t.allow.code.signing.", "このjarには、署名者証明書のNetscapeCertType拡張機能がコード署名を許可しないエントリが含まれています。" }, { ".{0}.extension.does.not.support.code.signing.", "[{0}拡張機能はコード署名をサポートしていません]" }, { "The.signer.s.certificate.chain.is.invalid.reason.1", "署名者の証明書チェーンが無効です。理由: %s" }, { "The.tsa.certificate.chain.is.invalid.reason.1", "TSA証明書チェーンが無効です。理由: %s" }, { "The.signer.s.certificate.is.self.signed.", "署名者の証明書は自己署名されています。" }, { "The.1.algorithm.specified.for.the.2.option.is.considered.a.security.risk.", "%1$sアルゴリズム(%2$sオプションに指定)は、セキュリティ・リスクとみなされます。" }, { "This.jar.contains.entries.whose.certificate.chain.is.invalid.reason.1", "このjarには、証明書チェーンが無効なエントリが含まれています。理由: %s" }, { "This.jar.contains.entries.whose.tsa.certificate.chain.is.invalid.reason.1", "このjarには、TSA証明書チェーンが無効なエントリが含まれています。理由: %s" }, { "no.timestamp.signing", "-tsaまたは-tsacertが指定されていないため、このjarにはタイムスタンプが付加されていません。タイムスタンプがないと、署名者証明書の有効期限(%1$tY-%1$tm-%1$td)後または将来の失効日後に、ユーザーはこのjarを検証できない可能性があります。" }, { "invalid.timestamp.signing", "タイムスタンプが無効です。有効なタイムスタンプがないと、署名者証明書の有効期限(%1$tY-%1$tm-%1$td)後に、ユーザーはこのjarを検証できない可能性があります。" }, { "no.timestamp.verifying", "このjarには、タイムスタンプがない署名が含まれています。タイムスタンプがないと、いずれかの署名者証明書の有効期限後に(早ければ%1$tY-%1$tm-%1$td)ユーザーはこのjarを検証できない可能性があります。" }, { "bad.timestamp.verifying", "このjarには、無効なタイムスタンプのある署名が含まれています。有効なタイムスタンプがないと、いずれかの署名者証明書の有効期限後に(早ければ%1$tY-%1$tm-%1$td)ユーザーはこのjarを検証できない可能性があります。\n詳細は、-J-Djava.security.debug=jarを指定してjarsignerを再実行してください。" }, { "The.signer.certificate.will.expire.on.1.", "署名者の証明書は%1$tY-%1$tm-%1$tdに期限切れになります。" }, { "The.timestamp.will.expire.on.1.", "タイムスタンプは%1$tY-%1$tm-%1$tdに期限切れになります。" }, { "signer.cert.expired.1.but.timestamp.good.2.", "署名者の証明書は%1$tY-%1$tm-%1$tdに期限切れになります。ただし、JARはタイムスタンプが%2$tY-%2$tm-%2$tdに期限切れになるまで有効です。" }, { "Unknown.password.type.", "不明なパスワード・タイプ: " }, { "Cannot.find.environment.variable.", "環境変数が見つかりません: " }, { "Cannot.find.file.", "ファイルが見つかりません: " } };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public Object[][] getContents() {
/* 304 */     return contents;
/*     */   }
/*     */ }


/* Location:              C:\Program Files\Java\jdk1.8.0_211\lib\tools.jar!\sun\security\tools\jarsigner\Resources_ja.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */